Vasiliy linked list
gorobec/ACO19TeamWork pull request #4
Opened 2017-04-22 18:24 UTC by vasiliypekhterev

The implementation and unit tests of the Linked List were added.

2017-04-22 22:40 UTC, gorobec commented on vasiliy/src/main/java/data_structures/MyLinkedList.java
> +        if (!checkIndex(index)) {
You will duplicate this check in method:
private Node findNode(int index) {
        if (!checkIndex(index) || isEmpty()) {
            return null;
        }

2017-04-22 22:42 UTC, gorobec commented on vasiliy/src/main/java/data_structures/MyLinkedList.java
> +        if (!checkIndex(index)) {
You will duplicate this check in method:
private Node findNode(int index) {
        if (!checkIndex(index) || isEmpty()) {
            return null;
        }

2017-04-22 22:44 UTC, gorobec commented on vasiliy/src/main/java/data_structures/MyLinkedList.java
> +        if (!checkIndex(index)) {
You will duplicate this check in method:
private Node findNode(int index) {
        if (!checkIndex(index) || isEmpty()) {
            return null;
        }

2017-04-22 22:44 UTC, gorobec commented on vasiliy/src/main/java/data_structures/MyLinkedList.java
> +        if (!checkIndex(index)) {
You will duplicate this check in method:
private Node findNode(int index) {
        if (!checkIndex(index) || isEmpty()) {
            return null;
        }

2017-04-22 22:46 UTC, gorobec commented on vasiliy/src/main/java/data_structures/MyLinkedList.java
> +        if (node == head) {
if (node == head) you will never reach this block, cause method will finish in previous block with the same statement

2017-04-22 22:47 UTC, gorobec requested changes
need work

2017-04-23 04:39 UTC, vasiliypekhterev commented
The bugs were fixed.

2017-04-23 04:39 UTC, vasiliypekhterev commented
The bugs were fixed.

2017-04-23 10:54 UTC, merged